
package VsitaControlador;

import IO.BaseDatosUsuario;
import Modelo.Usuario;
import javax.swing.JOptionPane;

public class Ventana_Bienvenida extends javax.swing.JFrame {

    Usuario user;
    Ventana_Loggin ventana_loggin;
    public Ventana_Bienvenida(Usuario user,Ventana_Loggin entrada) {
        initComponents();
        this.user = user;
        ventana_loggin = entrada;
        Tetxo_Bienvenida_Usuario.setText("Usuario " + this.user.getUsuario() + " Loggeado" );
    }

    public Ventana_Bienvenida() {
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_Bienvenida = new javax.swing.JLabel();
        Tetxo_Bienvenida_Usuario = new javax.swing.JLabel();
        Boton_CerrarSesion = new javax.swing.JButton();
        Boton_Modificar_Contraseña = new javax.swing.JButton();
        Campo_Contraseña_Modificada = new javax.swing.JPasswordField();
        Check_Box_Contrseña_Modificada = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Benvenid@");

        Texto_Bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Texto_Bienvenida.setText("BIenvenid@");

        Tetxo_Bienvenida_Usuario.setText("jLabel2");

        Boton_CerrarSesion.setText("Cerrar Sesion");
        Boton_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CerrarSesionActionPerformed(evt);
            }
        });

        Boton_Modificar_Contraseña.setText("Modificar Contraseña");
        Boton_Modificar_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Modificar_ContraseñaActionPerformed(evt);
            }
        });

        Check_Box_Contrseña_Modificada.setText("Mostrar");
        Check_Box_Contrseña_Modificada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_Box_Contrseña_ModificadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_Modificar_Contraseña)
                            .addComponent(Boton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tetxo_Bienvenida_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(Campo_Contraseña_Modificada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Check_Box_Contrseña_Modificada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Texto_Bienvenida)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Texto_Bienvenida)
                .addGap(18, 18, 18)
                .addComponent(Tetxo_Bienvenida_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(Boton_CerrarSesion)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_Contraseña_Modificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_Box_Contrseña_Modificada))
                .addGap(18, 18, 18)
                .addComponent(Boton_Modificar_Contraseña)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionActionPerformed
        this.setVisible(false);
        ventana_loggin.setVisible(true);
    }//GEN-LAST:event_Boton_CerrarSesionActionPerformed

    private void Boton_Modificar_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Modificar_ContraseñaActionPerformed
        if(String.valueOf(Campo_Contraseña_Modificada.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(null, "Contrseña Vacia");
            return;
        }
        user.setContraseña(String.valueOf(Campo_Contraseña_Modificada.getPassword()));
        BaseDatosUsuario.updateUsuario(user);
        JOptionPane.showMessageDialog(null, "Contraseña Modificada");
    }//GEN-LAST:event_Boton_Modificar_ContraseñaActionPerformed

    private void Check_Box_Contrseña_ModificadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_Box_Contrseña_ModificadaActionPerformed
        if(Check_Box_Contrseña_Modificada.isSelected()){
            Campo_Contraseña_Modificada.setEchoChar((char)0);
        }else{
            Campo_Contraseña_Modificada.setEchoChar('*');
        }
    }//GEN-LAST:event_Check_Box_Contrseña_ModificadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_CerrarSesion;
    private javax.swing.JButton Boton_Modificar_Contraseña;
    private javax.swing.JPasswordField Campo_Contraseña_Modificada;
    private javax.swing.JCheckBox Check_Box_Contrseña_Modificada;
    private javax.swing.JLabel Tetxo_Bienvenida_Usuario;
    private javax.swing.JLabel Texto_Bienvenida;
    // End of variables declaration//GEN-END:variables
}
